iapiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql
        app: phonebookapp
    spec:
      containers:
        - image: mysql: 5.7
          name: mysql
          ports:
          - name: mysql
            containerPort: 3306
          env: 
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysqldb-secret
                key: mysql-root-username
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysqldb-secret
                key: mysql-root-password
          volumeMounts:
            - name: mysql-storage
              mountPath: /data/db
      volumes:
        #- name: mongo-storage
        #  hostPath:
        #    path: /data/db
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    name: mysql
    app: phonebookapp
spec:
  selector:
    name: mysql
  type: ClusterIP
  ports:
    - name: db
      port: 3306
      targetPort: 3306
