apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result
spec:
  selector:
    name: result
  type: NodePort
  ports:
    - name: result
      port: 80
      nodePort: 30002
      targetPort: 80
