apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers: 
        - image: gulec2000/web-server
          imagePullPolicy: Always
          name: web-server
          ports: 
            - containerPort: 80
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: rootpassword
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: configfile
                  key: MYSQL_DATABASE
            - name: MYSQL_DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: configfile
                  key: MYSQL_DATABASE_HOST
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
