apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
        app: phonebookapp
    spec:
      containers: 
        - image: clarusways/phonebook
          imagePullPolicy: Always
          name: myweb
          ports: 
            - containerPort: 3000
          env:
            - name: "MYSQL_ROOT_PASSWORD"
              value: Pl123456789
            - name: "MYSQL_DATABASE"
              value: mysql-db
            - name: "MYSQL_DATABASE_HOST"
              value: "db-server"
            - name: "MYSQL_PASSWORD"
              value: admin
            - name: "MYSQL_USER"
              value: admin
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 80m
